"""Add tipo_sugestao to SugestaoProduto

Revision ID: 063a17eb3305
Revises: 
Create Date: 2024-08-06 14:06:35.726474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063a17eb3305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erro_log')
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.alter_column('codbar',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('sugestao',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('audio_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tipo_sugestao',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.alter_column('tipo_sugestao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('audio_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sugestao',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('codbar',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               nullable=False)

    op.create_table('erro_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('erro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('descricao_erro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data_hora', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
