"""Add tipo_sugestao to SugestaoProduto

Revision ID: 46f5d7cb7244
Revises: 
Create Date: 2024-07-11 11:39:26.653631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f5d7cb7244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_sugestao', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.drop_column('tipo_sugestao')

    # ### end Alembic commands ###
