"""Add tipo_sugestao to SugestaoProduto

Revision ID: 83939ab54a06
Revises: 46f5d7cb7244
Create Date: 2024-07-11 11:54:04.877046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83939ab54a06'
down_revision = '46f5d7cb7244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.alter_column('tipo_sugestao',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sugestao_produto', schema=None) as batch_op:
        batch_op.alter_column('tipo_sugestao',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
